### ISSUE TITLE
Fix "Create Wall" button

### ISSUE THREAD

**Issue by Nyx1on** [Nyx1on/Pathfinding-Visualizer#2]
Current behaviour:
•When clicked once on "Create Wall", it remains on focus.
•When clicked outside, ie the second time, for example while actually creating the wall, the button is released from focus.

Expected Behaviour:
•The button should remain in focus until clicked back on the same button.

**Comment by Joe-Mwangi** [comment]
can i you kindly assign me this issue

**Comment by Nyx1on** [comment]
> can i you kindly assign me this issue

Sure
