### ISSUE TITLE
Fix reset button

### ISSUE THREAD

**Issue by Nyx1on** [Nyx1on/Pathfinding-Visualizer#7]
### **Expected Behaviour:**
1.Reset button should clear all nodes that are visited, ie change isVisited to False
2.Reset button should not reset Walls.

**Comment by Sridharan2509** [comment]
Hi @Nyx1on , you can assign this issue to me. I can work on this.

**Comment by Nyx1on** [comment]
> Hi @Nyx1on , you can assign this issue to me. I can work on this.

Sure

**Comment by Sridharan2509** [comment]
Hi @Nyx1on, I have updated the code and tested. I have raised a PR from my forked repository (https://github.com/Nyx1on/Pathfinding-Visualizer/pull/8) . Please review and let me know if any changes required.

**Comment by Nyx1on** [comment]
Yes, thank you very much
